images_dir: ./images

charts:
  - filename: test1.png
    x_min_date: "2023-08-10"
    x_max_date: "2026-04-04"
    y_min: 40
    y_max: 290

  - filename: test2.png
    x_min_date: "2023-08-10"
    x_max_date: "2026-04-04"
    y_min: 85
    y_max: 125

output:
  figures_dir: figures
  csv_filename: timeseries.csv
